name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: maven:3-amazoncorretto-25-debian
    steps:
      - uses: actions/checkout@v7

      - name: cache maven deps
        uses: actions/cache@v6
        with:
          path: .m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: run tests
        run: mvn test -B -Dmaven.repo.local=.m2/repository

  container:
    name: container image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: set up buildx
        uses: docker/setup-buildx-action@v4

      - name: build image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
